name: meeting_scheduler
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.0
  pinput: ^2.2.30
  fpdart: ^0.3.0
  flutter_riverpod: ^2.1.1
  shared_preferences: ^2.2.2
  multiple_result: ^4.0.0
  image_picker: ^0.8.6
  pattern_formatter: ^3.0.0
  flutter_animate: ^2.1.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  path_provider: ^2.0.11
  dropdown_button2: ^2.3.8
  pull_to_refresh: ^2.0.0
  flutter_fadein: ^2.0.0
  connectivity_plus: ^3.0.3
  flutter_svg:
  loading_indicator: ^3.1.1
  riverpod_annotation:
  searchfield: ^0.8.7
  uuid: ^3.0.7
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  flutter_spinkit: ^5.2.0
  firebase_storage: ^11.5.2
  flutter_slidable: ^3.0.1
  stacked_listview: ^1.0.4
  country_code_picker: ^3.0.0
  flutter_screenutil: ^5.5.4
  sentry_flutter: ^7.13.2
  flutter_dotenv: ^5.1.0
  awesome_snackbar_content:
  calendar_timeline: ^1.1.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  http: ^1.1.2
  email_otp: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pedantic_mono: ^1.24.0+1
  riverpod_lint: ^2.3.6
  custom_lint:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/png/
    - assets/icons/
    - assets/fonts/SFPRODISPLAYMEDIUM.OTF
    - assets/fonts/SFPRODISPLAYREGULAR.OTF
    - .env
